# -*- coding: utf-8 -*-
"""
Daily Words Data File
Author: Rubby
Description: 中英对照 + 英/美音标 + 示例句
"""

CATEGORIES = {
    "Fruits": [
        ("苹果", "apple", "/ˈæp.əl/", "/ˈæp.əl/", "I eat an apple every morning."),
        ("香蕉", "banana", "/bəˈnɑː.nə/", "/bəˈnæn.ə/", "Bananas are rich in potassium."),
        ("橙子", "orange", "/ˈɒr.ɪndʒ/", "/ˈɔːr.ɪndʒ/", "Would you like some orange juice?"),
        ("葡萄", "grape", "/ɡreɪp/", "/ɡreɪp/", "These grapes taste sweet."),
        ("草莓", "strawberry", "/ˈstrɔː.bər.i/", "/ˈstrɔːˌbɛr.i/", "Strawberry jam is delicious."),
        ("西瓜", "watermelon", "/ˈwɔː.təˌmel.ən/", "/ˈwɔː.tɚˌmel.ən/", "We had watermelon at the picnic."),
        ("哈密瓜", "hami melon", "/ˈhæm.i ˈmel.ən/", "/ˈhæm.i ˈmel.ən/", "Hami melon is very juicy."),
        ("菠萝", "pineapple", "/ˈpaɪnˌæp.əl/", "/ˈpaɪnˌæp.əl/", "Pineapple on pizza is controversial."),
        ("桃子", "peach", "/piːtʃ/", "/piːtʃ/", "The peach is soft and ripe."),
        ("梨", "pear", "/peə/", "/per/", "She sliced a pear for dessert."),
        ("樱桃", "cherry", "/ˈtʃer.i/", "/ˈtʃer.i/", "The cake is topped with cherries."),
        ("柠檬", "lemon", "/ˈlem.ən/", "/ˈlem.ən/", "Add lemon to your tea."),
        ("青柠", "lime", "/laɪm/", "/laɪm/", "Lime adds a fresh flavor."),
        ("蓝莓", "blueberry", "/ˈbluːˌber.i/", "/ˈbluːˌbɛr.i/", "Blueberry muffins are my favorite."),
        ("黑莓", "blackberry", "/ˈblækˌber.i/", "/ˈblækˌbɛr.i/", "We picked blackberries in the woods."),
        ("覆盆子", "raspberry", "/ˈrɑːzˌber.i/", "/ˈræzˌbɛr.i/", "Raspberry sauce goes well with cheesecake."),
        ("猕猴桃", "kiwi", "/ˈkiː.wiː/", "/ˈkiː.wiː/", "Peel the kiwi before eating."),
        ("芒果", "mango", "/ˈmæŋ.ɡəʊ/", "/ˈmæŋ.ɡoʊ/", "Mango smoothies are refreshing."),
        ("椰子", "coconut", "/ˈkəʊ.kə.nʌt/", "/ˈkoʊ.kə.nʌt/", "Coconut water is hydrating."),
        ("木瓜", "papaya", "/pəˈpaɪ.ə/", "/pəˈpaɪ.ə/", "Papaya aids digestion."),
        ("百香果", "passion fruit", "/ˈpæʃ.ən fruːt/", "/ˈpæʃ.ən fruːt/", "Passion fruit has a unique aroma."),
        ("石榴", "pomegranate", "/ˈpɒm.ɪˌgræn.ɪt/", "/ˈpɑː.məˌgræn.ɪt/", "Pomegranate seeds are crunchy."),
        ("李子", "plum", "/plʌm/", "/plʌm/", "She ate a ripe plum."),
        ("杏", "apricot", "/ˈeɪ.prɪ.kɒt/", "/ˈeɪ.prɪ.kɑːt/", "Dried apricots are sweet."),
        ("葡萄柚", "grapefruit", "/ˈgreɪp.fruːt/", "/ˈgreɪp.fruːt/", "Grapefruit can be bitter."),
        ("柚子", "pomelo", "/ˈpɒm.ɪləʊ/", "/ˈpɑː.məˌloʊ/", "Pomelo is similar to grapefruit."),
        ("樱桃番茄", "cherry tomato", "/tʃer.i təˈmɑː.təʊ/", "/tʃer.i təˈmeɪ.toʊ/", "Add cherry tomatoes to the salad."),
        ("桑葚", "mulberry", "/ˈmʌlˌber.i/", "/ˈmʌlˌbɛr.i/", "Mulberries stain easily."),
        ("无花果", "fig", "/fɪɡ/", "/fɪɡ/", "Fresh figs are seasonal."),
        ("荔枝", "lychee", "/ˈliː.tʃiː/", "/ˈliː.tʃiː/", "Lychees have a floral taste."),
        ("龙眼", "longan", "/ˈlɒŋ.ɡən/", "/ˈlɑːŋ.ɡən/", "Longan is sweet and juicy."),
        ("山竹", "mangosteen", "/ˈmæŋ.ɡəˌstiːn/", "/ˈmæŋ.ɡoʊˌstiːn/", "Mangosteen is called the queen of fruits."),
        ("杨桃", "starfruit", "/ˈstɑː.fruːt/", "/ˈstɑːr.fruːt/", "Starfruit has a star shape when sliced."),
        ("蔓越莓", "cranberry", "/ˈkræn.bər.i/", "/ˈkræn.bɛr.i/", "Cranberry juice is tart."),
        ("枣", "jujube", "/ˈdʒuː.dʒuːb/", "/ˈdʒuː.dʒuːb/", "Jujube is often dried."),
        ("波罗蜜", "jackfruit", "/ˈdʒæk.fruːt/", "/ˈdʒæk.fruːt/", "Jackfruit can be used as a meat substitute."),
        ("榴莲", "durian", "/ˈdjʊə.ri.ən/", "/ˈdʊr.i.ən/", "Durian has a strong smell."),
        ("椰枣", "date", "/deɪt/", "/deɪt/", "Dates are very sweet."),
        ("橘子", "tangerine", "/ˌtæn.dʒəˈriːn/", "/ˌtæn.dʒəˈriːn/", "Tangerines are easy to peel."),
        ("青苹果", "green apple", "/ˌɡriːn ˈæp.əl/", "/ˌɡriːn ˈæp.əl/", "Green apples are sour."),
        ("火龙果", "dragon fruit", "/ˈdræɡ.ən fruːt/", "/ˈdræɡ.ən fruːt/", "Dragon fruit is colorful."),
        ("柿子", "persimmon", "/pəˈsɪm.ən/", "/pɚˈsɪm.ən/", "Persimmons are sweet when ripe."),
        ("李子干", "prune", "/pruːn/", "/pruːn/", "Prunes help digestion."),
        ("青枣", "green jujube", "/ɡriːn ˈdʒuː.dʒuːb/", "/ɡriːn ˈdʒuː.dʒuːb/", "Green jujubes are crisp."),
        ("杨梅", "bayberry", "/ˈbeɪˌber.i/", "/ˈbeɪˌbɛr.i/", "Bayberries are juicy and red."),
        ("番石榴", "guava", "/ˈɡwɑː.və/", "/ˈɡwɑː.və/", "Guava juice is refreshing."),
        ("柠檬片", "lemon slice", "/ˈlem.ən slaɪs/", "/ˈlem.ən slaɪs/", "Add a lemon slice to your water."),
        ("果酱", "jam", "/dʒæm/", "/dʒæm/", "I spread jam on toast."),
        ("水果沙拉", "fruit salad", "/fruːt ˈsæl.əd/", "/fruːt ˈsæl.əd/", "Fruit salad is healthy."),
        ("水果盘", "fruit platter", "/fruːt ˈplæt.ər/", "/fruːt ˈplæt.ɚ/", "We shared a fruit platter."),
        ("果汁", "juice", "/dʒuːs/", "/dʒuːs/", "Fresh juice is the best."),
        ("冰淇淋", "ice cream", "/ˈaɪs ˌkriːm/", "/ˈaɪs ˌkriːm/", "I like mango ice cream."),
        ("奶昔", "milkshake", "/ˈmɪlk.ʃeɪk/", "/ˈmɪlk.ʃeɪk/", "Chocolate milkshake is my favorite."),
        ("干果", "dried fruit", "/draɪd fruːt/", "/draɪd fruːt/", "Dried fruit is great for snacks.")
    ],
    "Vegetables": [
        ("胡萝卜", "carrot", "/ˈkær.ət/", "/ˈkær.ət/", "Carrots are good for your eyes."),
        ("土豆", "potato", "/pəˈteɪ.təʊ/", "/pəˈteɪ.toʊ/", "Mashed potatoes are creamy."),
        ("红薯", "sweet potato", "/swiːt pəˈteɪ.təʊ/", "/swiːt pəˈteɪ.toʊ/", "Sweet potatoes are nutritious."),
        ("西红柿", "tomato", "/təˈmɑː.təʊ/", "/təˈmeɪ.toʊ/", "Tomatoes are used in many sauces."),
        ("黄瓜", "cucumber", "/ˈkjuː.kʌm.bə/", "/ˈkjuː.kʌm.bɚ/", "Cucumber is refreshing."),
        ("洋葱", "onion", "/ˈʌn.jən/", "/ˈʌn.jən/", "Onions can make you cry."),
        ("大蒜", "garlic", "/ˈɡɑː.lɪk/", "/ˈɡɑːr.lɪk/", "Garlic adds strong flavor."),
        ("生姜", "ginger", "/ˈdʒɪn.dʒə/", "/ˈdʒɪn.dʒɚ/", "Ginger warms the body."),
        ("西兰花", "broccoli", "/ˈbrɒk.əl.i/", "/ˈbrɑː.kə.li/", "Broccoli is rich in fiber."),
        ("花菜", "cauliflower", "/ˈkɒl.ɪˌflaʊ.ə/", "/ˈkɑː.ləˌflaʊ.ɚ/", "Cauliflower rice is low-carb."),
        ("生菜", "lettuce", "/ˈlet.ɪs/", "/ˈlet.ɪs/", "Lettuce is used in salads."),
        ("菠菜", "spinach", "/ˈspɪn.ɪtʃ/", "/ˈspɪn.ɪtʃ/", "Spinach is high in iron."),
        ("卷心菜", "cabbage", "/ˈkæb.ɪdʒ/", "/ˈkæb.ɪdʒ/", "Cabbage can be fermented into kimchi."),
        ("蘑菇", "mushroom", "/ˈmʌʃ.ruːm/", "/ˈmʌʃ.ruːm/", "Mushrooms soak up sauces."),
        ("玉米", "corn", "/kɔːn/", "/kɔːrn/", "Corn on the cob is tasty."),
        ("豌豆", "peas", "/piːz/", "/piːz/", "Peas are small and sweet."),
        ("豆角", "green beans", "/ˌgriːn ˈbiːnz/", "/ˌgriːn ˈbiːnz/", "Green beans are crunchy."),
        ("青椒", "bell pepper", "/bel ˈpep.ə/", "/bel ˈpep.ɚ/", "Bell peppers come in many colors."),
        ("辣椒", "chili pepper", "/ˈtʃɪl.i/", "/ˈtʃɪl.i/", "Chili peppers add heat."),
        ("茄子", "eggplant", "/ˈeɡ.plɑːnt/", "/ˈɛɡˌplænt/", "Eggplant absorbs oil easily."),
        ("芹菜", "celery", "/ˈsel.ər.i/", "/ˈsel.ɚ.i/", "Celery is crunchy."),
        ("南瓜", "pumpkin", "/ˈpʌmp.kɪn/", "/ˈpʌmp.kɪn/", "Pumpkin soup is comforting."),
        ("西葫芦", "zucchini", "/zuːˈkiː.ni/", "/zuːˈkiː.ni/", "Zucchini noodles are popular."),
        ("芦笋", "asparagus", "/əˈspær.ə.ɡəs/", "/əˈspær.ə.ɡəs/", "Asparagus is in season in spring."),
        ("香葱", "scallion", "/ˈskæl.jən/", "/ˈskæl.jən/", "Scallions add freshness."),
        ("葱", "green onion", "/ˈɡriːn ˈʌn.jən/", "/ˈɡriːn ˈʌn.jən/", "Green onion is used in many dishes."),
        ("蒜苗", "garlic sprout", "/ˈɡɑː.lɪk spraʊt/", "/ˈɡɑːr.lɪk spraʊt/", "Garlic sprouts add flavor."),
        ("韭菜", "chives", "/tʃaɪvz/", "/tʃaɪvz/", "Chives are used as seasoning."),
        ("芥蓝", "Chinese kale", "/ˈtʃaɪˌniːz keɪl/", "/ˈtʃaɪˌniːz keɪl/", "Chinese kale is nutritious."),
        ("竹笋", "bamboo shoot", "/ˈbæm.buː ʃuːt/", "/ˈbæm.buː ʃuːt/", "Bamboo shoots are tender."),
        ("海带", "kelp", "/kelp/", "/kelp/", "Kelp is used in soups."),
        ("香菜", "cilantro", "/sɪˈlæn.trəʊ/", "/sɪˈlæn.troʊ/", "Cilantro divides opinions."),
        ("紫甘蓝", "red cabbage", "/red ˈkæb.ɪdʒ/", "/red ˈkæb.ɪdʒ/", "Red cabbage is colorful."),
        ("甜菜", "beetroot", "/ˈbiːt.ruːt/", "/ˈbiːt.ruːt/", "Beetroot can be roasted."),
        ("茼蒿", "crown daisy", "/kraʊn ˈdeɪ.zi/", "/kraʊn ˈdeɪ.zi/", "Crown daisy is aromatic."),
        ("香菇", "shiitake mushroom", "/ʃɪˈtɑː.keɪ/", "/ʃɪˈtɑː.ki/", "Shiitake mushrooms are flavorful."),
        ("金针菇", "enoki mushroom", "/ɪˈnəʊ.ki/", "/ɪˈnoʊ.ki/", "Enoki mushrooms are long and thin."),
        ("藕", "lotus root", "/ˈləʊ.təs ruːt/", "/ˈloʊ.təs ruːt/", "Lotus root is crunchy when stir-fried."),
        ("莴笋", "stem lettuce", "/stem ˈlet.ɪs/", "/stem ˈlet.ɪs/", "Stem lettuce is crisp and fresh."),
        ("豆芽", "bean sprout", "/biːn spraʊt/", "/biːn spraʊt/", "Bean sprouts are used in noodles."),
        ("苦瓜", "bitter melon", "/ˈbɪt.ə ˈmel.ən/", "/ˈbɪt.ɚ ˈmel.ən/", "Bitter melon has a distinct taste."),
        ("冬瓜", "winter melon", "/ˈwɪn.tə ˈmel.ən/", "/ˈwɪn.tɚ ˈmel.ən/", "Winter melon soup is cooling."),
        ("丝瓜", "loofah", "/ˈluː.fə/", "/ˈluː.fə/", "Loofah is tender when cooked."),
        ("山药", "yam", "/jæm/", "/jæm/", "Yam porridge is smooth."),
        ("芋头", "taro", "/ˈtɑː.rəʊ/", "/ˈtɑː.roʊ/", "Taro milk tea is popular."),
        ("地瓜叶", "sweet potato leaf", "/swiːt pəˈteɪ.tə liːf/", "/swiːt pəˈteɪ.toʊ liːf/",
         "Sweet potato leaves are edible."),
        ("香芋", "purple taro", "/ˈpɜː.pl̩ ˈtɑː.roʊ/", "/ˈpɝː.pəl ˈtɑː.roʊ/", "Purple taro is often used in desserts."),
        ("白萝卜", "white radish", "/waɪt ˈræd.ɪʃ/", "/waɪt ˈræd.ɪʃ/", "White radish soup is light."),
        ("胡萝卜片", "carrot slice", "/ˈkær.ət slaɪs/", "/ˈkær.ət slaɪs/", "Add carrot slices to the salad."),
        ("蔬菜汤", "vegetable soup", "/ˈvedʒ.tə.bəl suːp/", "/ˈvedʒ.tə.bəl suːp/", "Vegetable soup is healthy."),
        (
        "蔬菜沙拉", "vegetable salad", "/ˈvedʒ.tə.bəl ˈsæl.əd/", "/ˈvedʒ.tə.bəl ˈsæl.əd/", "Vegetable salad is fresh."),
        ("豆腐", "tofu", "/ˈtəʊ.fuː/", "/ˈtoʊ.fuː/", "Tofu is high in protein."),
        ("白菜", "Chinese cabbage", "/ˈtʃaɪˌniːz ˈkæb.ɪdʒ/", "/ˈtʃaɪˌniːz ˈkæb.ɪdʒ/",
         "Chinese cabbage is soft and sweet."),
        ("菠菜汁", "spinach juice", "/ˈspɪn.ɪtʃ dʒuːs/", "/ˈspɪn.ɪtʃ dʒuːs/", "Spinach juice is full of nutrients."),
        ("茄汁", "tomato sauce", "/təˈmɑː.təʊ sɔːs/", "/təˈmeɪ.toʊ sɔːs/", "Tomato sauce is used on pasta."),
        ("豆浆", "soy milk", "/sɔɪ mɪlk/", "/sɔɪ mɪlk/", "Soy milk is a common breakfast drink.")
    ],
    "Daily": [
        ("牙刷", "toothbrush", "/ˈtuːθ.brʌʃ/", "/ˈtuːθ.brʌʃ/", "Use your toothbrush twice a day."),
        ("牙膏", "toothpaste", "/ˈtuːθ.peɪst/", "/ˈtuːθ.peɪst/", "Don't forget the toothpaste."),
        ("牙线", "dental floss", "/ˈden.təl flɒs/", "/ˈden.təl flɔːs/", "Dental floss keeps gums healthy."),
        ("毛巾", "towel", "/ˈtaʊ.əl/", "/ˈtaʊ.əl/", "Grab a clean towel."),
        ("肥皂", "soap", "/səʊp/", "/soʊp/", "Wash your hands with soap."),
        ("洗手液", "hand soap", "/hænd səʊp/", "/hænd soʊp/", "We need more hand soap."),
        ("洗发水", "shampoo", "/ʃæmˈpuː/", "/ʃæmˈpuː/", "This shampoo smells nice."),
        ("护发素", "conditioner", "/kənˈdɪʃ.ən.ər/", "/kənˈdɪʃ.ən.ɚ/", "Use conditioner after shampoo."),
        ("沐浴露", "body wash", "/ˈbɒd.i wɒʃ/", "/ˈbɑː.di wɑːʃ/", "I prefer body wash to soap."),
        ("梳子", "comb", "/kəʊm/", "/koʊm/", "He combed his hair."),
        ("纸巾", "tissue", "/ˈtɪʃ.uː/", "/ˈtɪʃ.uː/", "Do you have a tissue?"),
        ("卫生纸", "toilet paper", "/ˈtɔɪ.lət ˌpeɪ.pə/", "/ˈtɔɪ.lət ˌpeɪ.pɚ/", "We ran out of toilet paper."),
        ("垃圾袋", "trash bag", "/træʃ bæɡ/", "/træʃ bæɡ/", "Replace the trash bag, please."),
        ("洗衣液", "laundry detergent", "/ˈlɔːn.dri dɪˈtɜː.dʒənt/", "/ˈlɔːn.dri dɪˈtɝː.dʒənt/", "Add the laundry detergent first."),
        ("衣架", "hanger", "/ˈhæŋ.ə/", "/ˈhæŋ.ɚ/", "Hang your coat on a hanger."),
        ("杯子", "cup", "/kʌp/", "/kʌp/", "I drink water from a cup."),
        ("水瓶", "water bottle", "/ˈwɔː.tə ˌbɒt.əl/", "/ˈwɑː.tɚ ˌbɑː.t̬əl/", "Bring your water bottle."),
        ("背包", "backpack", "/ˈbæk.pæk/", "/ˈbæk.pæk/", "She carries a backpack to school."),
        ("钱包", "wallet", "/ˈwɒl.ɪt/", "/ˈwɑː.lɪt/", "I left my wallet at home."),
        ("钥匙", "key", "/kiː/", "/kiː/", "Don't forget your keys."),
        ("雨伞", "umbrella", "/ʌmˈbrel.ə/", "/ʌmˈbrel.ə/", "Take an umbrella; it might rain."),
        ("手电筒", "flashlight", "/ˈflæʃ.laɪt/", "/ˈflæʃ.laɪt/", "Use a flashlight in the dark."),
        ("口罩", "mask", "/mɑːsk/", "/mæsk/", "Wear a mask on the subway."),
        ("创可贴", "band-aid", "/ˈbænd eɪd/", "/ˈbænd eɪd/", "Put a band-aid on the cut."),
        ("消毒湿巾", "disinfecting wipes", "/ˌdɪs.ɪnˈfekt.ɪŋ waɪps/", "/ˌdɪs.ɪnˈfekt.ɪŋ waɪps/", "Use disinfecting wipes for the table."),
        ("闹钟", "alarm clock", "/əˈlɑːm klɒk/", "/əˈlɑːrm klɑːk/", "Set your alarm clock for 7."),
        ("充电器", "charger", "/ˈtʃɑː.dʒə/", "/ˈtʃɑːr.dʒɚ/", "This charger is fast."),
        ("耳机", "headphones", "/ˈhed.foʊnz/", "/ˈhed.foʊnz/", "Use headphones on the bus."),
        ("电脑", "computer", "/kəmˈpjuː.tə/", "/kəmˈpjuː.tɚ/", "I work on a computer."),
        ("键盘", "keyboard", "/ˈkiː.bɔːd/", "/ˈkiː.bɔːrd/", "The keyboard is mechanical."),
        ("鼠标", "mouse", "/maʊs/", "/maʊs/", "The mouse is wireless."),
        ("剪刀", "scissors", "/ˈsɪz.əz/", "/ˈsɪz.ɚz/", "Use scissors carefully."),
        ("胶带", "tape", "/teɪp/", "/teɪp/", "We need clear tape."),
        ("订书机", "stapler", "/ˈsteɪ.plə/", "/ˈsteɪ.plɚ/", "Where is the stapler?"),
        ("记号笔", "marker", "/ˈmɑː.kə/", "/ˈmɑːr.kɚ/", "Use a marker to label the box."),
        ("笔记本", "notebook", "/ˈnəʊt.bʊk/", "/ˈnoʊt.bʊk/", "Write it in your notebook."),
        ("便签", "sticky notes", "/ˈstɪk.i nəʊts/", "/ˈstɪk.i noʊts/", "Leave a sticky note on the fridge."),
        ("遥控器", "remote control", "/rɪˌməʊt kənˈtrəʊl/", "/rɪˌmoʊt kənˈtroʊl/", "Use the remote control to change channels."),
        ("电视", "TV", "/ˈtiː.viː/", "/ˈtiː.viː/", "Turn off the TV before bed."),
        ("床", "bed", "/bed/", "/bed/", "Make your bed in the morning."),
        ("椅子", "chair", "/tʃeə/", "/tʃer/", "This chair is comfortable."),
        ("桌子", "table", "/ˈteɪ.bəl/", "/ˈteɪ.bəl/", "Dinner is on the table."),
        ("沙发", "sofa", "/ˈsəʊ.fə/", "/ˈsoʊ.fə/", "Sit on the sofa and relax."),
        ("灯", "lamp", "/læmp/", "/læmp/", "Turn on the lamp."),
        ("衣服", "clothes", "/kləʊðz/", "/kloʊðz/", "Fold your clothes."),
        ("鞋子", "shoes", "/ʃuːz/", "/ʃuːz/", "Take off your shoes at the door."),
        ("外套", "coat", "/kəʊt/", "/koʊt/", "Wear a coat; it's cold outside."),
        ("围巾", "scarf", "/skɑːf/", "/skɑːrf/", "She wore a warm scarf."),
        ("帽子", "hat", "/hæt/", "/hæt/", "Put on your hat."),
        ("手套", "gloves", "/ɡlʌvz/", "/ɡlʌvz/", "Wear gloves in winter."),
        ("手机", "mobile phone", "/ˈməʊ.baɪl fəʊn/", "/ˈmoʊ.bəl foʊn/", "Where is my mobile phone?"),
        ("相机", "camera", "/ˈkæm.rə/", "/ˈkæm.rə/", "He bought a new camera."),
        ("书", "book", "/bʊk/", "/bʊk/", "I read a book before bed."),
        ("铅笔", "pencil", "/ˈpen.səl/", "/ˈpen.səl/", "Sharpen your pencil."),
        ("橡皮", "eraser", "/ɪˈreɪ.zər/", "/ɪˈreɪ.zɚ/", "Use an eraser to correct mistakes."),
        ("日历", "calendar", "/ˈkæl.ən.də/", "/ˈkæl.ən.dɚ/", "Check the date on the calendar.")
    ]
}
